### ISSUE TITLE
gst_rtsp_media_factory_set_do_retransmission

### ISSUE THREAD

**Issue by alainpleno** [dusty-nv/jetson-utils#145]
I'm trying to compile on a Xavier NX (jetpack 4.6.1) and get the following error:

`$ make
[  1%] Building CXX object CMakeFiles/jetson-utils.dir/network/RTSPServer.cpp.o
/scratch/ALAIN/jetson-utils/network/RTSPServer.cpp: In member function ‘bool RTSPServer::AddRoute(const char*, GstElement*)’:
/scratch/ALAIN/jetson-utils/network/RTSPServer.cpp:278:2: error: ‘gst_rtsp_media_factory_set_do_retransmission’ was not declared in this scope
  gst_rtsp_media_factory_set_do_retransmission(factory, false);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/scratch/ALAIN/jetson-utils/network/RTSPServer.cpp:278:2: note: suggested alternative: ‘gst_rtsp_media_factory_set_retransmission_time’
  gst_rtsp_media_factory_set_do_retransmission(factory, false);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  gst_rtsp_media_factory_set_retransmission_time
CMakeFiles/jetson-utils.dir/build.make:4859: recipe for target 'CMakeFiles/jetson-utils.dir/network/RTSPServer.cpp.o' failed
make[2]: *** [CMakeFiles/jetson-utils.dir/network/RTSPServer.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/jetson-utils.dir/all' failed
make[1]: *** [CMakeFiles/jetson-utils.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
`

I went back to commit 91a2a9bb3b2b22892f90f9bc1661ee605a14ed63 and can compile.
not blocking in any way, this is just FYI.

**Comment by dusty-nv** [comment]
Thanks @alainpleno, added this to my todo list to investigate - I probably need to check the GStreamer version before calling that function.
